FROM docker.io/golang:bookworm as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

FROM alpine:3.17

WORKDIR /app

COPY --from=builder /app/main .

USER 1001

ENTRYPOINT ["/app/main"]

