---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  params:
    - name: CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
    - name: ARGS
      type: string
    - name: NODE_IMAGE
      type: string
      default: "quay.io/fedora/nodejs-18-minimal:latest"
  steps:
    - name: npm-run
      image: $(params.NODE_IMAGE)
      script: |
        npm $(params.ARGS)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
