---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: words-cicd-pipeline
spec:
  workspaces:
    - name: shared
  params:
    - name: IMAGE_NAME
      type: string
      default: "words"
    - name: IMAGE_REGISTRY
      type: string
      default: "image-registry.openshift-image-registry.svc:5000"
    - name: GIT_REPO
      type: string
      default: "https://github.com/beopencloud/openshift-developers"
    - name: GIT_REVISION
      type: string
      default: "master"
    - name: APP_PATH
      type: string
      default: "app/compreview-cicd/words"
  tasks:
    - name: fetch-repository
      # TODO
      params:
        # TODO
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"
      workspaces:
        # TODO

    - name: npm-install
    # TODO

    - name: npm-test
    # TODO

    - name: npm-lint
    # TODO

    - name: build-push-image
    # TODO

    - name: oc-deploy
    # TODO
